### PR TITLE
Dynamically add the browser name to message.file

### PR DESCRIPTION
**Pull request by InternalError503**
This change grabs the browsers localized name from the browser
brand.properties then passes this to the restart message.

This means if there is a translated word for Firefox it will show or if
the browsers name is not the hard-coded Firefox it will display that
name.

### CODE REVIEW

**Comment by InternalError503** [comment]
The feature was meant to be a separate request from the other 2 sorry about that still learning git.

**Comment by Aris-t2** [comment]
Hi.
thanks for the changes to dynamically add browsers name to messages files.

Sorry I can't pull these requests. I have to merge the changes locally with my current unreleased builds which also introduced a few new strings to the messages files.

Furthermore there is no need for an option to "remove" tab text shadow. CTR offers tab text color and shadow preferences which can be used to achieve this.
Set a transparent tab text shadow using e.g. rgba(0,0,0,0) and no new code has to be added to CTR. Transparent shadow equals removed shadow in this case.

All changes (except the shadow option) will be on CTR 1.3.0beta1.

**Comment by InternalError503** [comment]
Hi Aris

That's ok. Glad to help.

Yeah, the remove persona text shadow does removed more then just the tab's text shadow.

**With Shadow:**
shadow

**Without Shadow:**
no-shadow

It affects the bookmarks tool-bar and the menu-bar tool-bar, As shown in the above illustrations.
This works well with lighter colored personas under the Firefox preset (Australis)

**Comment by Aris-t2** [comment]
Makes sense. I've uploaded a new build containing an extended version of this new option to also affect navigation toolbars and add-on bars text for users, that are using text/icons+text modes.

I got mislead first, because you have added this option to tabs category where imo it makes more sense to be on "Toolbars (1)" category, since it affects primarily toolbars (now).

**Comment by InternalError503** [comment]
Yes, That would indeed be my fault sorry about that, I was unsure what category it should go under so i selected tabs as its primary.

Glad you were able to use it and :+1: on the improvement on it, I keep forgetting about the addon bar.

**Pull request closed without merging**
