### PR TITLE
Update options.dtd

### PR DESCRIPTION
**Pull request by ma2moto**

### CODE REVIEW

**Comment by Aris-t2** [comment]
Hi, do you have interest in keeping Japanese translation up to date? I had to remove it recently, because it contained too many outdated strings, but I would add it back, when you would want to keep it updated.

**Comment by ma2moto** [comment]
If you add it back, I will update it by the end of next month.

**Comment by Aris-t2** [comment]
Hi again,
I've added 'ja' locales files back to CTR.
https://github.com/Aris-t2/ClassicThemeRestorer/tree/master/xpi/locale/ja

**Comment by Aris-t2** [comment]
Japanese locale is on Github and on CTR beta releases, but not on 1.5.0 final. It will be added to final once it gets updated.
Do you have any new ETA on when this might happen?

**Pull request merged**
